name: Test action on PR comment
on:
  issue_comment:
    types: [created]

jobs:
  test-action:
    if: ${{ github.event.issue.pull_request &&
            ( github.event.comment.author_association == 'OWNER' ||
              github.event.comment.author_association == 'MEMBER' ||
              github.event.comment.author_association == 'COLLABORATOR' ) &&
            contains(github.event.comment.body, '```buildkite') }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Regex match
        uses: actions-ecosystem/action-regex-match@v2.0.0
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^```buildkite\r?\n([\s\S]*?)```'
          flags: gm
      - name: Dump Regex match
        env:
          REGEX_MATCH: "{\"PIPELINE\": ${{ toJson(steps.regex-match.outputs.group1) }} }"
        run: echo "$REGEX_MATCH"
      - name: Trigger Buildkite Pipeline
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env: 
          PIPELINE: "clima/actiontest"
          COMMIT: "HEAD"
          BRANCH: "master"
          MESSAGE: ":github: Triggered from a GitHub Action"
          BUILD_ENV_VARS: "{\"PIPELINE\": ${{ toJson(steps.regex-match.outputs.group1) }} }"
