name: Test action on PR comment
on:
  issue_comment:
    types: [created]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Test action on PR comment
        if: ${{ github.event.issue.pull_request && contains(["OWNER", "MEMBER", "COLLABORATOR"], github.event.comment.author_association) && contains(github.event.comment.body, '/foo') }}
        run: echo "Event triggered!"
